Added command line argument for base directory.

diff --git a/bin/wdi-init b/bin/wdi-init
--- a/bin/wdi-init
+++ b/bin/wdi-init
@@ -1,18 +1,7 @@
 #!/bin/bash
 
-TEST_MODE=false
-if [ "$(whoami)" == 'drmikeh' ]; then
-  TEST_MODE=true
-fi
-
-if $TEST_MODE ; then
-  BASE_DIR=~/tmp2
-else
-  BASE_DIR=~
-fi
-
-VERSION=0.1.3
-WDI_DIR=$BASE_DIR/ga/wdi
+VERSION=0.1.4
+WDI_DIR=${WDI_DIR:=~/ga/wdi}
 WDI_CLASSWORK_REPO=https://github.com/ga-students/WDI-ATL-4-Classwork
 
 #
@@ -51,33 +40,39 @@ git_clone() {
 # Main Script
 #
 
-while [[ $# > 0 ]]
-do
-  key="$1"
-
-  case $key in
-    -v|--version)
-    echo "wdi-init $VERSION"
-    exit 0
-    ;;
-
-    -h|--help)
-    echo "Usage: wdi-init [-v] [-h]"
-    echo "General options:"
-    echo "  -v, --version  # Print the version information"
-    echo "  -h, --help     # Print usage and options"
-    exit 0
-    ;;
-
-    *)
-    echo "Unrecognized option: $key"
-    exit 0
-    ;;
+while getopts ":vhd:" opt; do
+  case $opt in
+    v)
+      echo "wdi-init $VERSION"
+      exit 0
+      ;;
+    d)
+      WDI_DIR=$OPTARG
+      echo "NOTE: WDI_DIR is set to $WDI_DIR"
+      ;;
+    h)
+      echo "Usage: wdi-init [-v] [-h] [-d <wdi_dir>]"
+      echo "General options:"
+      echo "  -v             # Print the version information"
+      echo "  -h             # Print usage and options"
+      echo "  -d <wdi_dir>   # Sets the base wdi directory, default is ~/ga/wdi"
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
   esac
 done
 
-echo "==> Creating the directory structure for the GA WDI Class."
-echo "==> This script is non-destructive. It will simply add directories where needed."
+echo "==> Creating the directory structure for the GA WDI Class using"
+echo "==> base directory = $WDI_DIR"
+echo "==> Note: this script is non-destructive. It will simply add directories where needed."
+confirm
 echo
 create_dir $WDI_DIR
 create_dir $WDI_DIR/projects
@@ -87,24 +82,5 @@ create_dir $WDI_DIR/projects/project_3
 create_dir $WDI_DIR/projects/project_4
 git_clone $WDI_CLASSWORK_REPO
 
-if $TEST_MODE ; then
-  echo
-  echo "==> Results of find"
-  find $BASE_DIR | grep -v .git
-  echo
-  echo "==> Contents of Classwork README.md"
-  cat $WDI_DIR/classwork/README.md
-fi
-
 echo
-
-#
-# Cleanup
-#
-if $TEST_MODE ; then
-  echo "==> Cleanup"
-  echo "==> Removing $WDI_DIR"
-  rm -rf $WDI_DIR
-fi
-
 echo "==> All done!"
